// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQYSvGaJxx8NNFVakjXzXLKoghVoZ4m28',
    appId: '1:735025156467:web:308d685864592118c27506',
    messagingSenderId: '735025156467',
    projectId: 'legal-scholar-app',
    authDomain: 'legal-scholar-app.firebaseapp.com',
    storageBucket: 'legal-scholar-app.appspot.com',
    measurementId: 'G-YJCCP3WW63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFCqHQEKI5fp3DlgOn0uegjNZTP5K6PYw',
    appId: '1:735025156467:android:6d9ea483d5735287c27506',
    messagingSenderId: '735025156467',
    projectId: 'legal-scholar-app',
    storageBucket: 'legal-scholar-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVJifAbSLvEGdkf654bhcp2-Jm5p11084',
    appId: '1:735025156467:ios:3ca5196861e478dac27506',
    messagingSenderId: '735025156467',
    projectId: 'legal-scholar-app',
    storageBucket: 'legal-scholar-app.appspot.com',
    iosBundleId: 'com.example.legalScholarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVJifAbSLvEGdkf654bhcp2-Jm5p11084',
    appId: '1:735025156467:ios:3ca5196861e478dac27506',
    messagingSenderId: '735025156467',
    projectId: 'legal-scholar-app',
    storageBucket: 'legal-scholar-app.appspot.com',
    iosBundleId: 'com.example.legalScholarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQYSvGaJxx8NNFVakjXzXLKoghVoZ4m28',
    appId: '1:735025156467:web:9b8fbb0764c0d076c27506',
    messagingSenderId: '735025156467',
    projectId: 'legal-scholar-app',
    authDomain: 'legal-scholar-app.firebaseapp.com',
    storageBucket: 'legal-scholar-app.appspot.com',
    measurementId: 'G-XFZ6ES1ZHQ',
  );
}
